/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: uptime_report_msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "uptime_report_msg.pb-c.h"
void   uptime_report_msg__init
                     (UptimeReportMsg         *message)
{
  static UptimeReportMsg init_value = UPTIME_REPORT_MSG__INIT;
  *message = init_value;
}
size_t uptime_report_msg__get_packed_size
                     (const UptimeReportMsg *message)
{
  assert(message->base.descriptor == &uptime_report_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uptime_report_msg__pack
                     (const UptimeReportMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uptime_report_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uptime_report_msg__pack_to_buffer
                     (const UptimeReportMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uptime_report_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UptimeReportMsg *
       uptime_report_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UptimeReportMsg *)
     protobuf_c_message_unpack (&uptime_report_msg__descriptor,
                                allocator, len, data);
}
void   uptime_report_msg__free_unpacked
                     (UptimeReportMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &uptime_report_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor uptime_report_msg__field_descriptors[3] =
{
  {
    "mac_address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UptimeReportMsg, mac_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UptimeReportMsg, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UptimeReportMsg, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uptime_report_msg__field_indices_by_name[] = {
  1,   /* field[1] = description */
  0,   /* field[0] = mac_address */
  2,   /* field[2] = uptime */
};
static const ProtobufCIntRange uptime_report_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor uptime_report_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uptime_report_msg",
  "UptimeReportMsg",
  "UptimeReportMsg",
  "",
  sizeof(UptimeReportMsg),
  3,
  uptime_report_msg__field_descriptors,
  uptime_report_msg__field_indices_by_name,
  1,  uptime_report_msg__number_ranges,
  (ProtobufCMessageInit) uptime_report_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
