/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: uptime_report_msg.proto */

#ifndef PROTOBUF_C_uptime_5freport_5fmsg_2eproto__INCLUDED
#define PROTOBUF_C_uptime_5freport_5fmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _UptimeReportMsg UptimeReportMsg;


/* --- enums --- */


/* --- messages --- */

struct  _UptimeReportMsg
{
  ProtobufCMessage base;
  char *mac_address;
  char *description;
  uint32_t uptime;
};
#define UPTIME_REPORT_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uptime_report_msg__descriptor) \
    , NULL, NULL, 0 }


/* UptimeReportMsg methods */
void   uptime_report_msg__init
                     (UptimeReportMsg         *message);
size_t uptime_report_msg__get_packed_size
                     (const UptimeReportMsg   *message);
size_t uptime_report_msg__pack
                     (const UptimeReportMsg   *message,
                      uint8_t             *out);
size_t uptime_report_msg__pack_to_buffer
                     (const UptimeReportMsg   *message,
                      ProtobufCBuffer     *buffer);
UptimeReportMsg *
       uptime_report_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uptime_report_msg__free_unpacked
                     (UptimeReportMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UptimeReportMsg_Closure)
                 (const UptimeReportMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor uptime_report_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_uptime_5freport_5fmsg_2eproto__INCLUDED */
